---
version: '2.4'
services:
  pwr_stat:
    container_name: pwr_stat
    hostname: pwr_stat
    restart: always
    image: dwinks/pwrstat_docker:latest
    devices:
    - /dev/bus/usb/003/003:/dev/bus/usb/001/001
    volumes:
    - /docker_binds/pwr_stat/pwrstat.yaml:/pwrstat.yaml:ro
    healthcheck:
    test: ["CMD", "curl", "-sI", "http://127.0.0.1:5002/pwrstat"]
    interval: 30s
    timeout: 1s
    retries: 24
    privileged: true
    network_mode: host
